### ISSUE TITLE
Additional installation notes

### ISSUE THREAD

**Issue by rogererens** [snowcloud/ct-snowhite#1]
On my Ubuntu machine, before running the pip install -r requirements.txt I had to install the libpq-dev libraries (my system already had the python-dev package that are also needed according to
http://goshawknest.wordpress.com/2011/02/16/how-to-install-psycopg2-under-virtualenv/)

Being in a virtualenv, I'd rather use
/path/to/python/in/virtualenv/python manage.py syncdb
rather than ./manage.py syncdb
as manage.py has a shebang pointing to the system python.

The post_install file is not in the same directory as manage.py, so a
cd ..
command is needed in the instruction. Besides, it's executable already so no need for
chmod +x post_install
Maybe the post_install script ought to use the virtualenvs python, too?
MIght be solved by 'activating' the virtualenv and just typing 'python'

After post_install finishes, I guess django should be started with
python manage.py runserver
?

Do you have some screenshots so we know which kind of views to expect?

Cheers,

Roger

**Comment by snowcloud** [comment]
Thanks Roger.

I've now removed psycopg2 from the requirements.txt - the default install just uses sqlite3 which is now part of the python install.

I've also improved the installation guidance in README.rst and fixed a few problems with the fixtures.

This now installs cleanly on my Mac OSX setup here. It might be easier for you to do a fresh installation.

Please note, the group and template pages are not formatting properly at the moment. These applications are just about to be updated with the new UI changes already in ct-snowhite. I'm waiting for some users to confirm they are happy with the changes before I push them to the master branches of all the framework apps. That should be in the next few weeks.

If you want the new UI now, switch to the restyle branches in ct-groups and ct-template - installed into ct-snowhite/src

cheers.

**Comment by rogererens** [comment]
Great, looks way better now!

One issue left: I cannot log in with the superuser created in the
./manage.py syncdb step. Using ./manage.py createsuperuser works,
though.

Cheers,

Roger

On Thu, Jan 12, 2012 at 13:56, Derek Hoy
reply@reply.github.com
wrote:

**Comment by snowcloud** [comment]
Ah, good catch. It's overwritten when post_install loads the users fixture.

I'll sort it.

**Comment by snowcloud** [comment]
Fixed now.
